<?php

/**
 * BaseDownload
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property blob $description
 * @property string $file
 * @property integer $sections_id
 * @property string $type
 * @property Section $section
 * 
 * @method integer  getId()          Returns the current record's "id" value
 * @method string   getName()        Returns the current record's "name" value
 * @method blob     getDescription() Returns the current record's "description" value
 * @method string   getFile()        Returns the current record's "file" value
 * @method integer  getSectionsId()  Returns the current record's "sections_id" value
 * @method string   getType()        Returns the current record's "type" value
 * @method Section  getSection()     Returns the current record's "section" value
 * @method Download setId()          Sets the current record's "id" value
 * @method Download setName()        Sets the current record's "name" value
 * @method Download setDescription() Sets the current record's "description" value
 * @method Download setFile()        Sets the current record's "file" value
 * @method Download setSectionsId()  Sets the current record's "sections_id" value
 * @method Download setType()        Sets the current record's "type" value
 * @method Download setSection()     Sets the current record's "section" value
 * 
 * @package    Eddyjim
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDownload extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('Downloads');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'unique' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 45,
             ));
        $this->hasColumn('description', 'blob', 65535, array(
             'type' => 'blob',
             'length' => 65535,
             ));
        $this->hasColumn('file', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('sections_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('type', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 45,
             ));


        $this->index('fk_Downloads_Sections1_idx', array(
             'fields' => 
             array(
              0 => 'sections_id',
             ),
             ));
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Section as section', array(
             'local' => 'sections_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));
    }
}