<?php

/**
 * BaseBannerPicture
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $banner_id
 * @property string $picture
 * @property integer $order
 * @property Banner $banner
 * @property Banner $Banner
 * 
 * @method integer       getId()        Returns the current record's "id" value
 * @method integer       getBannerId()  Returns the current record's "banner_id" value
 * @method string        getPicture()   Returns the current record's "picture" value
 * @method integer       getOrder()     Returns the current record's "order" value
 * @method Banner        getBanner()    Returns the current record's "banner" value
 * @method Banner        getBanner()    Returns the current record's "Banner" value
 * @method BannerPicture setId()        Sets the current record's "id" value
 * @method BannerPicture setBannerId()  Sets the current record's "banner_id" value
 * @method BannerPicture setPicture()   Sets the current record's "picture" value
 * @method BannerPicture setOrder()     Sets the current record's "order" value
 * @method BannerPicture setBanner()    Sets the current record's "banner" value
 * @method BannerPicture setBanner()    Sets the current record's "Banner" value
 * 
 * @package    Eddyjim
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBannerPicture extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('BannerPictures');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'unique' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('banner_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('picture', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 45,
             ));
        $this->hasColumn('order', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));


        $this->index('fk_BannerPictures_Banners1_idx', array(
             'fields' => 
             array(
              0 => 'banner_id',
             ),
             ));
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Banner as banner', array(
             'local' => 'banner_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('Banner', array(
             'local' => 'banner_id',
             'foreign' => 'id'));
    }
}