<?php

/**
 * BaseBlog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property integer $section_id
 * @property string $icon
 * @property Section $section
 * @property Section $Section
 * @property Doctrine_Collection $Publications
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method string              getTitle()        Returns the current record's "title" value
 * @method integer             getSectionId()    Returns the current record's "section_id" value
 * @method string              getIcon()         Returns the current record's "icon" value
 * @method Section             getSection()      Returns the current record's "section" value
 * @method Section             getSection()      Returns the current record's "Section" value
 * @method Doctrine_Collection getPublications() Returns the current record's "Publications" collection
 * @method Blog                setId()           Sets the current record's "id" value
 * @method Blog                setTitle()        Sets the current record's "title" value
 * @method Blog                setSectionId()    Sets the current record's "section_id" value
 * @method Blog                setIcon()         Sets the current record's "icon" value
 * @method Blog                setSection()      Sets the current record's "section" value
 * @method Blog                setSection()      Sets the current record's "Section" value
 * @method Blog                setPublications() Sets the current record's "Publications" collection
 * 
 * @package    Eddyjim
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBlog extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('Blogs');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'unique' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('section_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('icon', 'string', 45, array(
             'type' => 'string',
             'length' => 45,
             ));


        $this->index('fk_Blogs_Sections_idx', array(
             'fields' => 
             array(
              0 => 'section_id',
             ),
             ));
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Section as section', array(
             'local' => 'section_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('Section', array(
             'local' => 'section_id',
             'foreign' => 'id'));

        $this->hasMany('Publication as Publications', array(
             'local' => 'id',
             'foreign' => 'blogs_id'));
    }
}