<?php

/**
 * BaseSectionBanner
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $section_id
 * @property integer $banner_id
 * @property Section $section
 * @property Banner $banner
 * @property Section $Section
 * @property Banner $Banner
 * 
 * @method integer       getSectionId()  Returns the current record's "section_id" value
 * @method integer       getBannerId()   Returns the current record's "banner_id" value
 * @method Section       getSection()    Returns the current record's "section" value
 * @method Banner        getBanner()     Returns the current record's "banner" value
 * @method Section       getSection()    Returns the current record's "Section" value
 * @method Banner        getBanner()     Returns the current record's "Banner" value
 * @method SectionBanner setSectionId()  Sets the current record's "section_id" value
 * @method SectionBanner setBannerId()   Sets the current record's "banner_id" value
 * @method SectionBanner setSection()    Sets the current record's "section" value
 * @method SectionBanner setBanner()     Sets the current record's "banner" value
 * @method SectionBanner setSection()    Sets the current record's "Section" value
 * @method SectionBanner setBanner()     Sets the current record's "Banner" value
 * 
 * @package    Eddyjim
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSectionBanner extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('Sections_has_Banners');
        $this->hasColumn('section_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('banner_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));


        $this->index('fk_Sections_has_Banners_Banners1_idx', array(
             'fields' => 
             array(
              0 => 'banner_id',
             ),
             ));
        $this->index('fk_Sections_has_Banners_Sections1_idx', array(
             'fields' => 
             array(
              0 => 'section_id',
             ),
             ));
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Section as section', array(
             'local' => 'section_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('Banner as banner', array(
             'local' => 'banner_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('Section', array(
             'local' => 'section_id',
             'foreign' => 'id'));

        $this->hasOne('Banner', array(
             'local' => 'banner_id',
             'foreign' => 'id'));
    }
}