<?php

/**
 * BannerPictureTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BannerPictureTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BannerPictureTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BannerPicture');
    }
}