<?php

/**
 * BannerStyleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BannerStyleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BannerStyleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BannerStyle');
    }
}