<?php

/**
 * DownloadTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DownloadTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DownloadTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Download');
    }
}