<?php

/**
 * SocialNetworkTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SocialNetworkTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SocialNetworkTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SocialNetwork');
    }
}