<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/02/18 16:00:35

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=Eddyjim',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
