detect_relations: true
options:
  collate: utf8_general_ci
  charset: utf8
  type: InnoDB

SocialNetwork:
  tableName: SocialNetworks
  columns:
    id:
      type: integer(4)
      primary: true
      unique: true
      notnull: true
      autoincrement: true
    name:
      type: string(45)
      notnull: true
    link:
      type: blob(65535)
      notnull: true
    icon:
      type: string(255)
      notnull: true
    order:
      type: integer(4)

Blog:
  tableName: Blogs
  columns:
    id:
      type: integer(4)
      primary: true
      unique: true
      notnull: true
      autoincrement: true
    title:
      type: string(255)
      notnull: true
    section_id:
      type: integer(4)
      notnull: true
    icon:
      type: string(45)
  relations:
    section:
      class: Section
      local: section_id
      foreign: id
      foreignAlias: Blogs
      onDelete: CASCADE
      onUpdate: CASCADE
  indexes:
    fk_Blogs_Sections_idx:
      fields: [section_id]

Section:
  tableName: Sections
  columns:
    id:
      type: integer(4)
      primary: true
      unique: true
      notnull: true
      autoincrement: true
    name:
      type: string(45)
      notnull: true
    icon:
      type: string(45)
    order:
      type: integer(4)
    Pages_id:
      type: integer(4)
      notnull: true
  relations:
    page:
      class: Page
      local: Pages_id
      foreign: id
      foreignAlias: Sections
      onDelete: CASCADE
      onUpdate: CASCADE
    banners:
      class: Banner
      foreignAlias: Sections
      refClass: SectionBanner
      local: section_id
      foreign: banner_id
  indexes:
    fk_Sections_Pages1_idx:
      fields: [Pages_id]

BannerPicture:
  tableName: BannerPictures
  columns:
    id:
      type: integer(4)
      primary: true
      unique: true
      notnull: true
      autoincrement: true
    banner_id:
      type: integer(4)
      notnull: true
    picture:
      type: string(45)
      notnull: true
    order:
      type: integer(4)
  relations:
    banner:
      class: Banner
      local: banner_id
      foreign: id
      foreignAlias: BannerPictures
      onDelete: CASCADE
      onUpdate: CASCADE
  indexes:
    fk_BannerPictures_Banners1_idx:
      fields: [banner_id]

Banner:
  tableName: Banners
  columns:
    id:
      type: integer(4)
      primary: true
      unique: true
      notnull: true
      autoincrement: true
    banner_style_id:
      type: integer(4)
      primary: true
      notnull: true
  relations:
    bannerStyle:
      class: BannerStyle
      local: banner_style_id
      foreign: id
      foreignAlias: Banners
      onDelete: CASCADE
      onUpdate: CASCADE
  indexes:
    fk_Banners_BannerStyles1_idx:
      fields: [banner_style_id]

SectionBanner:
  tableName: Sections_has_Banners
  columns:
    section_id:
      type: integer(4)
      primary: true
      notnull: true
    banner_id:
      type: integer(4)
      primary: true
      notnull: true
  relations:
    section:
      class: Section
      local: section_id
      foreign: id
      foreignAlias: SectionBanner
      onDelete: CASCADE
      onUpdate: CASCADE
    banner:
      class: Banner
      local: banner_id
      foreign: id
      foreignAlias: SectionBanner
      onDelete: CASCADE
      onUpdate: CASCADE
  indexes:
    fk_Sections_has_Banners_Banners1_idx:
      fields: [banner_id]
    fk_Sections_has_Banners_Sections1_idx:
      fields: [section_id]

Publication:
  tableName: Publications
  columns:
    id:
      type: integer(4)
      primary: true
      unique: true
      notnull: true
      autoincrement: true
    title:
      type: string(45)
      notnull: true
    description:
      type: string(45)
      notnull: true
    blogs_id:
      type: integer(4)
      notnull: true
  relations:
    blog:
      class: Blog
      local: blogs_id
      foreign: id
      foreignAlias: Publications
      onDelete: CASCADE
      onUpdate: CASCADE
  indexes:
    fk_Publications_Blogs1_idx:
      fields: [blogs_id]

Comment:
  tableName: Comments
  columns:
    id:
      type: integer(4)
      primary: true
      unique: true
      notnull: true
      autoincrement: true
    user_id:
      type: string(45)
      notnull: true
    description:
      type: blob(65535)
      notnull: true
    Publications_id:
      type: integer(4)
    Comments_id:
      type: integer(4)
  relations:
    Publication:
      class: Publication
      local: Publications_id
      foreign: id
      foreignAlias: Comments
      onDelete: CASCADE
      onUpdate: CASCADE
    Comment:
      class: Comment
      local: Comments_id
      foreign: id
      foreignAlias: Comments
      onDelete: CASCADE
      onUpdate: CASCADE
  indexes:
    fk_Comments_Publications1_idx:
      fields: [Publications_id]
    fk_Comments_Comments1_idx:
      fields: [Comments_id]

Download:
  tableName: Downloads
  columns:
    id:
      type: integer(4)
      primary: true
      unique: true
      notnull: true
      autoincrement: true
    name:
      type: string(45)
      notnull: true
    description:
      type: blob(65535)
    file:
      type: string(255)
      notnull: true
    sections_id:
      type: integer(4)
      notnull: true
    type:
      type: string(45)
      notnull: true
  relations:
    section:
      class: Section
      local: sections_id
      foreign: id
      foreignAlias: Downloads
      onDelete: CASCADE
      onUpdate: CASCADE
  indexes:
    fk_Downloads_Sections1_idx:
      fields: [sections_id]

BannerStyle:
  tableName: BannerStyles
  columns:
    id:
      type: integer(4)
      primary: true
      unique: true
      notnull: true
      autoincrement: true
    name:
      type: string(45)
      notnull: true
    description:
      type: string(255)
    direction:
      type: string(45)
    effect:
      type: string(45)

Page:
  tableName: Pages
  columns:
    id:
      type: integer(4)
      primary: true
      unique: true
      notnull: true
      autoincrement: true
    name:
      type: string(45)
      notnull: true
    icon:
      type: string(45)
      notnull: true

